default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  database: postgres
  username: postgres
  password: 1234

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *default
